### ISSUE TITLE
Invert Caries Progress Chart

### ISSUE THREAD

**Issue by kerti** [rrmdn/idcra-client#3]
## Summary

We need to invert the Caries Progress Chart so that the green is on top, like so:

```
0  _ _ _ _ >
1  |
2  |
3  |
4  v
```

Priority: High
Due: Before Nov 20th

**Comment by rrmdn** [comment]
I have never seen any kind of chart this in this form, is this for sure @kerti ? Because I don't think the library would support this weird-looking chart

**Comment by rrmdn** [comment]
Turned out the library has been supporting that kind of chart since 2017, sending you a PR asap

**Comment by rrmdn** [comment]
Solved by #7
